dist: bionic
language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get install python3 git
  - sudo apt-get install ruby jq wget graphviz
  - sudo snap install go
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i *.deb
  - sudo gem install asciidoctor asciidoctor-diagram
  - git clone https://git.sr.ht/~sircmpwn/openring && cd openring && go build

script:
  - make build

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.76.0

deploy:
  local_dir: "./public/"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: gh-pages
  on:
    branch: master

